name: Publish npm Package

on:
  release:
    branches:
      - master

jobs:
  prepublish:
    name: Pre-Publish Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10.x
      fail-fast: true

    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm test

  publish:
    name: Publish Build Artifact
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 10.x
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://npm.pkg.github.com/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
